site_name: WDK Documentation
docs_dir: ../docs

theme:
  name: material
  features:
    - navigation.top
    - navigation.indexes
  palette:
    scheme: default
    primary: white
    accent: blue

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Getting Started: getting-started.md
  - Concepts: concepts.md
  - Guides:
    - FirstOrNullExpressionTool: FirstOrNullExpressionTool.md
    - ToolOutputs: ToolOutputs.md
